server:
  port: 7002

app:
  security:
    jwt:
      issuer: ecommerce
      atexpirationtimeinmin: 15
      rtexpirationtimeinmin: 360
    key:
      keyType: shared
      useEnvVar: false
      keyEnvVar: environment
      secretKey: fe80::e9ce:670:ac50:89bc:fe80::4418:5b6c:1df3:4a06

spring:
  datasource:
    url: jdbc:postgresql://dpg-d3e3pm7diees73fostkg-a.oregon-postgres.render.com:5432/ecommerce_ashar?sslmode=require
    username: ecommerce_ashar_user
    password: 8WDoRRfn9lO0rbpjam4PYr8GWKWOFN5T
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      default_schema: orders