app:
  security:
    jwt:
      issuer: ecommerce
      atexpirationtimeinmin: 15
      rtexpirationtimeinmin: 360
    key:
      keyType: shared
      useEnvVar: false
      keyEnvVar: environment
      secretKey: fe80::e9ce:670:ac50:89bc
